import { cookies } from "next/headers";
import { AuthProvider } from "../components/context/AuthContext";
import { ScoreProvider } from "../components/context/scoreContext";

import './globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const cookie= await cookies();
  const accessToken=cookie.get('accessToken')?.value || null;
  return (
    <html lang="en">
      
      <body className="min-h-screen bg-linear-to-t from-sky-500 to-indigo-500" >

        <AuthProvider initialToken={accessToken}> 
         <ScoreProvider> 
        {children}
        </ScoreProvider>
        </AuthProvider>
        </body>
    </html>
  )
}
